version: "3.8"

services:
  redis:
    image: redis:6.0.7-alpine
    volumes:
      - redis_data:/data
    networks:
      - redis_network
  postgres:
    image: postgres:12.4-alpine
    env_file:
      - .env
    volumes:
      - ./tools/postgres_init_scripts/create_dbs.sh:/docker-entrypoint-initdb.d/create_dbs.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
  celery_beat:
    image: trader/trader
    env_file:
      - .env
    environment:
      - CELERY_REDIS_HOST=redis
    command: celery -A trader.tasks beat --loglevel=INFO
    volumes:
      - .:/app
    networks:
      - redis_network
    depends_on:
      - redis
    container_name: celery_beat
  celery_worker:
    image: trader/trader
    env_file:
      - .env
    environment:
      - CELERY_REDIS_HOST=redis
      - CACHE_REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    command: celery -A trader.tasks worker --loglevel=INFO --concurrency=2
    volumes:
      - .:/app
    networks:
      - redis_network
      - postgres_network
    depends_on:
      - redis
      - postgres
    container_name: celery_worker
  data_feed_monitor:
    image: trader/trader
    env_file:
      - .env
    environment:
      - CELERY_REDIS_HOST=redis
      - CACHE_REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    command: python run_data_feed_monitor.py
    volumes:
      - .:/app
    networks:
      - redis_network
      - postgres_network
    depends_on:
      - redis
      - postgres
    container_name: data_feed_monitor

networks:
  redis_network:
    driver: bridge
  postgres_network:
    driver: bridge
volumes:
  redis_data:
  postgres_data:
  metabase_data:
