version: "3.8"

services:
  redis:
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
  metabase:
    ports:
      - "3000:3000"
  pgadmin:
    image: dpage/pgadmin4:5.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
    ports:
      - "15432:80"
    depends_on:
      - postgres

volumes:
  pgadmin_data:
