version: "3.8"

services:
  selenium:
    image: selenium/standalone-chrome:3.141.59
    networks:
      - selenium_network
    ports:
      - "4444:4444"
    shm_size: 2gb

networks:
  selenium_network:
    driver: bridge
