import os


CACHE_REDIS_HOST = os.environ["CACHE_REDIS_HOST"]
CACHE_REDIS_PORT = os.environ["CACHE_REDIS_PORT"]
CACHE_REDIS_DATABASE = os.environ["CACHE_REDIS_DATABASE"]

CELERY_REDIS_HOST = os.environ["CELERY_REDIS_HOST"]
CELERY_REDIS_PORT = os.environ["CELERY_REDIS_PORT"]
CELERY_REDIS_DATABASE = os.environ["CELERY_REDIS_DATABASE"]

POSTGRES_USER = os.environ["POSTGRES_USER"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
POSTGRES_HOST = os.environ["POSTGRES_HOST"]
POSTGRES_PORT = os.environ["POSTGRES_PORT"]
POSTGRES_DATABASE = os.environ["POSTGRES_DATABASE"]

REMOTE_WEBDRIVER_HOST = os.environ["REMOTE_WEBDRIVER_HOST"]
REMOTE_WEBDRIVER_PORT = os.environ["REMOTE_WEBDRIVER_PORT"]
