import os


REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = os.environ["REDIS_PORT"]
REDIS_DATABASE = os.environ["REDIS_DATABASE"]

POSTGRES_USER = os.environ["POSTGRES_USER"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
POSTGRES_HOST = os.environ["POSTGRES_HOST"]
POSTGRES_PORT = os.environ["POSTGRES_PORT"]
POSTGRES_DATABASE = os.environ["POSTGRES_DATABASE"]

REMOTE_WEBDRIVER_HOST = os.environ["REMOTE_WEBDRIVER_HOST"]
REMOTE_WEBDRIVER_PORT = os.environ["REMOTE_WEBDRIVER_PORT"]
