version: "3.8"

services:
  metabase:
    image: metabase/metabase:v0.40.3.1
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - JAVA_TIMEZONE=UTC
    volumes:
      - metabase_data:/metabase-data
    networks:
      - postgres_network
    depends_on:
      - postgres

networks:
  postgres_network:
    driver: bridge
volumes:
  metabase_data:
